import { readFile, writeFile } from "node:fs/promises";

interface InputRow { [key: string]: unknown }
interface NormalizedRow { id: string; name: string; normalizedName: string; entityType: string; stateCode: string | null; districtCode: string | null; subDistrictCode: string | null; blockCode: string | null; villageCode: string | null; lgdCode: string | null; pincode: string | null; parentId: string | null; source: string; sourceId: string | null; aliases: string[]; isActive: boolean; metadata: Record<string, string> }

function normalize(value: string): string { return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLocaleLowerCase().trim().replace(/\s+/g, " "); }
function value(row: InputRow, names: string[]): string | null { for (const name of names) { const item = row[name] ?? row[name.toLocaleLowerCase()]; if (typeof item === "string" && item.trim()) return item.trim(); } return null; }
function entityType(row: InputRow): string { const valueText = normalize(value(row, ["entityType", "entity_type", "type", "local_body_type"]) ?? ""); if (valueText.includes("village")) return "VILLAGE"; if (valueText.includes("district")) return "DISTRICT"; if (valueText.includes("sub district") || valueText.includes("subdistrict")) return "SUB_DISTRICT"; if (valueText.includes("block")) return "BLOCK"; if (valueText.includes("local body") || valueText.includes("municip")) return "MUNICIPAL_CORPORATION"; return "LOCALITY"; }
function normalizeRow(row: InputRow, index: number): NormalizedRow | null { const name = value(row, ["name", "Name", "village_name", "district_name", "local_body_name"]); if (!name) return null; const lgdCode = value(row, ["lgdCode", "lgd_code", "LGD code", "code"]); return { id: `lgd-${lgdCode ?? index + 1}`, name, normalizedName: normalize(name), entityType: entityType(row), stateCode: value(row, ["stateCode", "state_code", "state_lgd_code"]), districtCode: value(row, ["districtCode", "district_code", "district_lgd_code"]), subDistrictCode: value(row, ["subDistrictCode", "sub_district_code"]), blockCode: value(row, ["blockCode", "block_code"]), villageCode: value(row, ["villageCode", "village_code"]), lgdCode, pincode: value(row, ["pincode", "pin_code", "PIN Code"]), parentId: value(row, ["parentId", "parent_id"]), source: "DATA_GOV_IN_LGD", sourceId: value(row, ["sourceId", "source_id"]), aliases: [], isActive: true, metadata: { importedAt: new Date().toISOString() } }; }
function parseCsv(text: string): InputRow[] { const lines = text.split(/\r?\n/).filter((line) => line.trim()); if (!lines.length) return []; const headers = lines[0].split(",").map((header) => header.trim()); return lines.slice(1).map((line) => { const cells = line.split(","); return Object.fromEntries(headers.map((header, index) => [header, cells[index]?.trim() ?? ""])); }); }
async function main(): Promise<void> { const input = process.argv[2]; const output = process.argv[3] ?? "data/location/lgd-normalized.json"; if (!input) throw new Error("Usage: tsx scripts/location/ingest-lgd.ts <official-json-or-csv> [output]"); const text = await readFile(input, "utf8"); const parsed: unknown = input.toLocaleLowerCase().endsWith(".json") ? JSON.parse(text) : parseCsv(text); const rows = Array.isArray(parsed) ? parsed.filter((row): row is InputRow => typeof row === "object" && row !== null) : []; const normalized = rows.map(normalizeRow).filter((row): row is NormalizedRow => row !== null); await writeFile(output, JSON.stringify({ source: "DATA_GOV_IN_LGD", updatedAt: new Date().toISOString(), rows: normalized }, null, 2), "utf8"); console.log(`Normalized ${normalized.length} LGD rows into ${output}`); }
void main();
