import type { AuthorityCandidate } from "./types";

export const LOCAL_AUTHORITY_DATA: AuthorityCandidate[] = [
  {
    id: "mh-nashik-rdd-road",
    state: "Maharashtra",
    district: "Nashik",
    category: "Rural development",
    department: "Rural Development and Panchayat Raj Department",
    publicAuthority: "Zilla Parishad Nashik - Rural Development Department",
    aliases: ["road", "roads", "road repair", "gaon ka road", "village road", "pavement", "contractor", "sadak", "रस्ता"],
    portalName: "Maharashtra RTI portal",
    portalUrl: "https://rtionline.maharashtra.gov.in/",
    sourceTitle: "Maharashtra Rural Development and Panchayat Raj Department",
    sourceUrl: "https://rdd.maharashtra.gov.in/",
    verifiedAt: "2026-08-27",
    active: true,
  },
  {
    id: "mh-nashik-school-education",
    state: "Maharashtra",
    district: "Nashik",
    category: "School education",
    department: "School Education and Sports Department",
    publicAuthority: "Zilla Parishad Nashik - Education Department",
    aliases: ["school", "classroom", "teacher", "school building", "midday meal", "शाळा"],
    portalName: "Maharashtra RTI portal",
    portalUrl: "https://rtionline.maharashtra.gov.in/",
    sourceTitle: "Maharashtra School Education and Sports Department",
    sourceUrl: "https://education.maharashtra.gov.in/",
    verifiedAt: "2026-08-27",
    active: true,
  },
  {
    id: "mh-nashik-water-supply",
    state: "Maharashtra",
    district: "Nashik",
    category: "Water supply and sanitation",
    department: "Water Supply and Sanitation Department",
    publicAuthority: "Maharashtra Jeevan Pradhikaran - Nashik Division",
    aliases: ["water", "tap", "pipeline", "drinking water", "jal jeevan", "पाणी"],
    portalName: "Maharashtra RTI portal",
    portalUrl: "https://rtionline.maharashtra.gov.in/",
    sourceTitle: "Maharashtra Jeevan Pradhikaran",
    sourceUrl: "https://mjp.maharashtra.gov.in/",
    verifiedAt: "2026-08-27",
    active: true,
  },
  {
    id: "mh-nashik-revenue-land",
    state: "Maharashtra",
    district: "Nashik",
    category: "Revenue and land records",
    department: "Revenue and Forest Department",
    publicAuthority: "Office of the District Collector, Nashik",
    aliases: ["land", "property", "7/12", "mutation", "survey", "collector", "जमीन"],
    portalName: "Nashik district official website",
    portalUrl: "https://nashik.gov.in/",
    sourceTitle: "Nashik District Administration",
    sourceUrl: "https://nashik.gov.in/",
    verifiedAt: "2026-08-27",
    active: true,
  },
  {
    id: "mh-nashik-public-health",
    state: "Maharashtra",
    district: "Nashik",
    category: "Public health",
    department: "Public Health Department",
    publicAuthority: "District Health Office, Zilla Parishad Nashik",
    aliases: ["hospital", "clinic", "medicine", "health centre", "ambulance", "आरोग्य"],
    portalName: "Nashik district official website",
    portalUrl: "https://nashik.gov.in/",
    sourceTitle: "Nashik District Administration",
    sourceUrl: "https://nashik.gov.in/",
    verifiedAt: "2026-08-27",
    active: true,
  },
];
